config/routes.rb
Rails.application.routes.draw do
  resources :homes
  devise_for :user, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'user/:id' => 'registrations#show', as: "show_profile"
    get 'users'    => 'registrations#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/homepage/index'
  get '/homepage/new'

  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :agent, class_name: "User", optional: true
  belongs_to :owner, class_name: "User", optional: true
  has_many :links, dependent: :destroy

  accepts_nested_attributes_for :links, allow_destroy: true, reject_if: :all_blank

  # Refile home image
  attachment :main_image
  attachment :additional_image

  def user_authorized?(asking_user)
    owner == asking_user || agent == asking_user
  end
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :home
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Refile profile image for agents
  attachment :profile_image

  # Adding a scope for agents
  scope :agents, -> { where(is_agent: true)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def index
    @recent_homes = Home.last(3)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: [:show, :new, :edit, :update, :destroy]

  # GET /homes
  def index
    @homes = params[:search] ? build_response_to_search_params(params) :
                               Home.all.order(price: :asc)
  end

  # GET /homes/1
  def show
  end

  # GET /homes/new
  def new
    @agents = User.agents
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
    @agents = User.agents
    unless @home.user_authorized?(current_user)
      flash[:notice] = 'Only the home owner may edit the home'
      redirect_to homes_path
    end
  end

  # POST /homes
  def create
    @home = Home.new(home_params)
    @home.owner = current_user

    if @home.save
      redirect_to @home, notice: 'Home was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /homes/1
  def update
    unless @home.user_authorized?(current_user)
      flash[:notice] = 'Only the home owner may edit the home'
      redirect_to homes_path

      return
    end

    if @home.update(home_params)
      redirect_to @home, notice: 'Home was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /homes/1
  def destroy
    unless @home.user_authorized?(current_user)
      flash[:notice] = 'Only the home owner may edit the home'
      redirect_to homes_path

      return
    end

    @home.delete
    redirect_to homes_url, notice: 'Home was successfully destroyed.'
  end

  private
  def set_home
    @home = Home.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def home_params
    params.require(:home).permit(:main_image, :additional_image, :address, :beds, :baths, :square_footage, :price, :description, :agent_id, links_attributes: [ :url, :description ])
  end

  def build_response_to_search_params(params)
    homes = Home.all

    # price
    homes = if !params[:search][:price][:max].empty? && !params[:search][:price][:min].empty?
              homes.where("price >= ? AND price <= ?", params[:search][:price][:min], params[:search][:price][:max])
            elsif !params[:search][:price][:max].empty?
              homes.where("price <= ?", params[:search][:price][:max])
            elsif !params[:search][:price][:min].empty?
              homes.where("price >= ?", params[:search][:price][:min])
            else
              homes
            end

    # Square Footage
    homes = if !params[:search][:square_footage][:max].empty? && !params[:search][:square_footage][:min].empty?
              homes.where("square_footage >= ? AND square_footage <= ?", params[:search][:square_footage][:min], params[:search][:square_footage][:max])
            elsif !params[:search][:square_footage][:max].empty?
              homes.where("square_footage <= ?", params[:search][:square_footage][:max])
            elsif !params[:search][:square_footage][:min].empty?
              homes.where("square_footage >= ?", params[:search][:square_footage][:min])
            else
              homes
            end
    # beds
    homes = if !params[:search][:beds][:max].empty? && !params[:search][:beds][:min].empty?
              homes.where("beds >= ? AND beds <= ?", params[:search][:beds][:min], params[:search][:beds][:max])
            elsif !params[:search][:beds][:max].empty?
              homes.where("beds <= ?", params[:search][:beds][:max])
            elsif !params[:search][:beds][:min].empty?
              homes.where("beds >= ?", params[:search][:beds][:min])
            else
              homes
            end

    # baths
    homes = if !params[:search][:baths][:max].empty? && !params[:search][:baths][:min].empty?
              homes.where("baths >= ? AND baths <= ?", params[:search][:baths][:min], params[:search][:baths][:max])
            elsif !params[:search][:baths][:max].empty?
              homes.where("baths <= ?", params[:search][:baths][:max])
            elsif !params[:search][:baths][:min].empty?
              homes.where("baths >= ?", params[:search][:baths][:min])
            else
              homes
            end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def index
    @users = User.agents
  end

  def show
    set_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def sign_up_params
    params.require(:user).permit(:profile_image, :name, :phone, :address, :is_agent, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:profile_image, :name, :phone, :address, :is_agent, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def setup_home(home)
    home.links ||= Link.new
    3.times { home.links.build }
    home
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/homepage/index.html.erb
<div class="jumbotron homepage-jumbotron">
  <div class="jumbo-container">
    <div class="col-lg-10">
      <h1>Find your next home</h1>
      <%= form_tag homes_path, class: "form-inline", method: "get" do %>
        <div class="form-group">
          <label> Price Min</label>
          <%= number_field_tag "search[price][min]", class: "form-control" %>
        </div>
        <div class="form-group">
          <label> Price Max</label>
          <%= number_field_tag "search[price][max]", class: "form-control" %>
        </div>
        <div class="form-group">
          <label> Square Ft Min</label>
          <%= number_field_tag "search[square_footage][min]", class: "form-control" %>
        </div>
        <div class="form-group">
          <label> Square Ft Max</label>
          <%= number_field_tag "search[square_footage][max]", class: "form-control" %>
        </div>
        <div class="form-group">
          <label> Beds Min</label>
          <%= number_field_tag "search[beds][min]", class: "form-control" %>
        </div>

        <div class="brick-search-pair">
          <div class="form-group">
            <label> Square Ft Min</label>
            <%= number_field_tag "search[square_footage][min]", class: "form-control" %>
          </div>
          <div class="form-group">
            <label> Square Ft Max</label>
            <%= number_field_tag "search[square_footage][max]", class: "form-control" %>
          </div>
        </div>

        <div class="brick-search-pair">
          <div class="form-group">
            <label> Beds Min</label>
            <%= number_field_tag "search[beds][min]", class: "form-control" %>
          </div>
          <div class="form-group">
            <label> Beds Max</label>
            <%= number_field_tag "search[beds][max]", class: "form-control" %>
          </div>
        </div>

        <div class="brick-search-pair">
          <div class="form-group">
            <label> Baths Min</label>
            <%= number_field_tag "search[baths][min]", class: "form-control" %>
          </div>
          <div class="form-group">
            <label> Baths Max</label>
            <%= number_field_tag "search[baths][max]", class: "form-control" %>
          </div>
        </div>
      </div>

        <div class="brick-search-submit">
          <div class="form-group">
              <button type="submit" class="btn btn-default">Submit</button>
          </div>
        </div>
      <% end %>

  </div>
</div>

<div class="page-header homepage-homes-section">
  <!-- What if there were only one or two homes in the whole system, this would be a lie -->
  <!-- What if there were NO homes in the system, maybe we don't show this at all -->
  <% if @recent_homes.any? %>
    <h2>Featured homes:</h2>
  <% end %>
</div>

<div class="row">
<% @recent_homes.each do |home| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= link_to home do %>
        <%= attachment_image_tag(home, :main_image) %>
      <% end%>
      <div class="caption">
        <%= link_to home do %>
        <h3><%= home.address %></h3>
        <% end%>
        <p><%= home.description %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/homes/_form.html.erb
<%= form_for(setup_home(@home), html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @home.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h4>

      <ul>
        <% @home.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <ul>
        <% @home.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label "Main Image", class: "col-sm-2 control-label" %>
    <%= f.attachment_field :main_image %><br />
  </div>

  <div class="form-group field form-inline">
    <%= f.label "Additional Images (optional)", class: "col-sm-2 control-label" %>
    <%= f.attachment_field :additional_image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :beds, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :beds, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :baths, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :baths, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :square_footage, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :square_footage, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :price, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Agent", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= collection_select(:home, :agent_id, @agents, :id, :name, {class: "form-control"}) %>
    </div>
  </div>


  <div class="form-control">
    Add some Links:
  </div>
  <br>

  <%= f.fields_for :links do |ff| %>
    <div class="form-group">
      <%= ff.label :url, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= ff.text_field :url, class: "form-control" %>
      </div>
      <%= ff.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= ff.text_field :description, class: "form-control" %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/homes/edit.html.erb
<div class="page-header">
  <%= link_to homes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @home, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing home</h1>
</div>

<%= render 'form' %>

app/views/homes/index.html.erb
<div class="container">
  <div class="page-header">
    <%= link_to new_home_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Home
    <% end %>
    <h1>Listing homes</h1>
  </div>

  <div id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <% @homes.each.with_index do |home, index| %>
        <li data-target="#myCarousel" data-slide-to="<%= index %>"></li>
      <% end %>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <% @homes.each.with_index do |home, i| %>
        <div data-index="<%= i %>" class="item <%= i == 0 ? "active": "" %>">
          <%= attachment_image_tag(home, :main_image) %>
          <div class="carousel-caption"><h4><%= home.address %></h4></div>
        </div>
      <% end %>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <br><br>

  <%= form_tag homes_path, class: "form-inline", method: "get" do %>
    <div class="form-group">
      <label> Price Min</label>
      <%= number_field_tag "search[price][min]", nil, class: "form-control" %>
    </div>
    <div class="form-group">
      <label> Price Max</label>
      <%= number_field_tag "search[price][max]", nil, class: "form-control" %>
    </div>
    <div class="form-group">
      <label> Square Ft Min</label>
      <%= number_field_tag "search[square_footage][min]", nil, class: "form-control" %>
    </div>
    <div class="form-group">
      <label> Square Ft Max</label>
      <%= number_field_tag "search[square_footage][max]", nil, class: "form-control" %>
    </div>
    <div class="form-group">
      <label> Beds Min</label>
      <%= number_field_tag "search[beds][min]", nil, class: "form-control" %>
    </div>
    <div class="form-group">
      <label> Beds Max</label>
      <%= number_field_tag "search[beds][max]", nil, class: "form-control" %>
    </div>
    <div class="form-group">
      <label> Baths Min</label>
      <%= number_field_tag "search[baths][min]", nil, class: "form-control" %>
    </div>
    <div class="form-group">
      <label> Baths Max</label>
      <%= number_field_tag "search[baths][max]", nil, class: "form-control" %>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
  <% end %>
  <div class="table-responsive container">
    <table class="table table-hover list-of-homes">
      <thead>
        <tr>
          <th>Address</th>
          <th>Beds</th>
          <th>Baths</th>
          <th>Square footage</th>
          <th>Price</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <%- @homes.each.with_index do |home, index| %>
        <tr class="<%= index == 0 ? "hovered" : "" %>">
          <td><%= home.address %></td>
          <td><%= home.beds %></td>
          <td><%= home.baths %></td>
          <td><%= home.square_footage %></td>
          <td><%= number_to_currency(home.price) %></td>
          <td><%= home.description.truncate_words(15) %></td>
          <td>
            <%= link_to home do %>
              <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
            <% end %>
          </td>
          <td>
            <%= link_to edit_home_path(home) do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            <% end %>
          </td>
          <td>
            <%= link_to home, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/homes/new.html.erb
<div class="container">

  <div class="page-header">
    <%= link_to homes_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <h1>New home</h1>
  </div>

  <%= render 'form' %>
</div>

app/views/homes/show.html.erb
<div class="container">
  <div class="page-header">
    <%= link_to homes_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <%= link_to edit_home_path(@home), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
    <% end %>
    <h2><%= @home.address %></h2>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="row">
        <div class="col-xs-8 col-sm-6">
          <% if @home.main_image %>
            <%= image_tag attachment_url(@home, :main_image, :fill, 300, 300) %>
          <% end %>
          <h3><%= @home.beds %> Bedrooms, <%= @home.baths %> bathrooms</h3>
        </div>
        <div class="col-xs-4 col-sm-6">
          <% if @home.additional_image %>
          <%= image_tag attachment_url(@home, :additional_image, :fill, 300, 300) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-9">
      <h4><%= @home.square_footage %> square feet and only <%= number_to_currency(@home.price) %></h4>
    </div>
  </div>
  <p><%= @home.description %></p>

        <% if @home.owner %>
          <dt>Owner:</dt>
          <dd><%= @home.owner.name %></dd>
        <% end %>

        <% if @home.agent %>
          <dt>Agent:</dt>
          <dd><%= link_to @home.agent.name, show_profile_path(@home.agent) %></dd>
        <%else%>
          <dt>associated agent</dt>
          <dd>Agent's info to follow</dd>
        <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("bricks-logo.gif", size: "70x50"), root_path, class: "logo navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <%= link_to "Buy", homes_path, class: "navbar-brand" %>
        </ul>
        <ul class="nav navbar-nav">
          <%= link_to "Sell", new_home_path, class: "navbar-brand" %>
        </ul>
        <ul class="nav navbar-nav">
          <li><%= link_to "Agents", users_path, class: "navbar-brand" %></li>
        </ul>
        <div class="nav navbar-nav navbar-right">
          <%- if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", "user/#{current_user.id}" %></li>
                <li><%= link_to('Log out', destroy_user_session_path, :method => :delete) %></li>
              </ul>
            </li>
          <%else%>
            <ul class="nav navbar-nav">
              <%=link_to "Sign up", new_user_registration_path, class: "navbar-brand"%>
            </ul>
            <ul class="nav navbar-nav">
              <%=link_to "Log in", new_user_session_path, class: "navbar-brand"%>
            </ul>
          <%end%>
        </div>
      </div>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
  </div>
    <%= yield %>

  <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <hr class="small">
                    <div class="footer-left">
                        <p class="text-muted">Copyright © 2016 BrickHaus. All rights reserved.
                          <%= link_to "http://www.hud.gov/offices/fheo/index.cfm" do %>
                            <%= image_tag('equal_housing.png', size: "13x13") %> Fair Housing and Equal Opportunity.
                          <% end %>
                          </p>
                    </div>
                    <div class="footer-right">
                    <ul class="list-inline">
                        <li>
                            <a href="https://www.facebook.com/TheIronYardTampa/"><i class="fa fa-facebook fa-fw fa-2x"></i></a>
                        </li>
                        <li>
                            <a href="https://goo.gl/6IU1Tc"><i class="fa fa-twitter fa-fw fa-2x"></i></a>
                        </li>
                        <li>
                            <a href="http://goo.gl/RJBw4y"><i class="fa fa-dribbble fa-fw fa-2x"></i></a>
                        </li>
                    </ul>
                  </div>
                </div>
            </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg" style="display: block; position: fixed;"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>
  </body>
  </body>
  </html>

</body>
</html>